"""
sheets.py — Google Sheets integration via OAuth 2.0

Uses token.json generated by oauth_setup.py (or auth_google.py).
Never uses google.auth.default() — works outside Colab too.
"""

import os
import logging
from datetime import datetime
from pathlib import Path

import gspread
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow

logger = logging.getLogger(__name__)

# Scopes required for Sheets + Drive (to create/find spreadsheets)
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file",
]

SHEET_COLUMNS = ["Title", "Author", "Year", "ISBN", "Genre", "Pages", "Cover URL", "Date Added"]


def get_credentials(
    token_path: str = "token.json",
    credentials_path: str = "credentials.json",
) -> Credentials:
    """
    Load OAuth credentials from token.json.
    If token is expired — refresh automatically.
    If token.json doesn't exist — raise with instructions.
    """
    token_file = Path(token_path)
    creds_file = Path(credentials_path)

    creds = None

    if token_file.exists():
        creds = Credentials.from_authorized_user_file(str(token_file), SCOPES)

    # Refresh if expired
    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            # Save refreshed token
            token_file.write_text(creds.to_json())
            logger.info("OAuth token refreshed successfully")
        except Exception as e:
            logger.warning(f"Token refresh failed: {e} — re-auth needed")
            creds = None

    if not creds or not creds.valid:
        if creds_file.exists():
            # Run OAuth flow in local server mode
            flow = InstalledAppFlow.from_client_secrets_file(str(creds_file), SCOPES)
            creds = flow.run_local_server(port=0)
            token_file.write_text(creds.to_json())
            logger.info(f"New OAuth token saved to {token_path}")
        else:
            raise FileNotFoundError(
                f"Neither {token_path} nor {credentials_path} found.\n"
                "Run: python bookshelf/oauth_setup.py\n"
                "Or download credentials.json from Google Cloud Console."
            )

    return creds


class BookshelfSheet:
    """
    Manages a Google Sheet for book catalog.
    Auto-creates sheet and header row if needed.
    """

    def __init__(
        self,
        sheet_name: str = "Bookshelf Catalog",
        token_path: str = "token.json",
        credentials_path: str = "credentials.json",
    ):
        self.sheet_name = sheet_name
        self.token_path = token_path
        self.credentials_path = credentials_path
        self._client: gspread.Client | None = None
        self._sheet: gspread.Worksheet | None = None
        self._sheet_url: str | None = None

    def _connect(self):
        """Lazy connect — only when first needed."""
        if self._client is not None:
            return

        creds = get_credentials(self.token_path, self.credentials_path)
        self._client = gspread.authorize(creds)
        logger.info("Connected to Google Sheets")

    def _get_sheet(self) -> gspread.Worksheet:
        """Get or create the spreadsheet and worksheet."""
        if self._sheet is not None:
            return self._sheet

        self._connect()

        # Try to open existing spreadsheet
        try:
            spreadsheet = self._client.open(self.sheet_name)
            logger.info(f"Opened existing spreadsheet: {self.sheet_name}")
        except gspread.SpreadsheetNotFound:
            # Create new one
            spreadsheet = self._client.create(self.sheet_name)
            logger.info(f"Created new spreadsheet: {self.sheet_name}")

        self._sheet_url = spreadsheet.url
        worksheet = spreadsheet.sheet1

        # Ensure header row exists
        existing = worksheet.row_values(1)
        if existing != SHEET_COLUMNS:
            worksheet.clear()
            worksheet.append_row(SHEET_COLUMNS)
            logger.info("Header row written")

        self._sheet = worksheet
        return self._sheet

    def get_url(self) -> str:
        """Return the URL of the spreadsheet."""
        self._get_sheet()  # ensures _sheet_url is set
        return self._sheet_url or "URL not available"

    def get_all_books(self) -> list[dict]:
        """Return all books as list of dicts."""
        sheet = self._get_sheet()
        records = sheet.get_all_records()
        return records

    def add_books(self, books: list[dict]) -> tuple[list[dict], list[dict]]:
        """
        Add books to the sheet, skipping duplicates.

        Args:
            books: list of dicts with keys matching SHEET_COLUMNS

        Returns:
            (added, skipped) — two lists of book dicts
        """
        sheet = self._get_sheet()
        existing = self.get_all_books()

        # Build dedup sets
        existing_isbns = {
            b["ISBN"].strip()
            for b in existing
            if b.get("ISBN") and b["ISBN"].strip() not in ("", "N/A")
        }
        existing_title_author = {
            (b["Title"].lower().strip(), b["Author"].lower().strip())
            for b in existing
            if b.get("Title") and b.get("Author")
        }

        added = []
        skipped = []
        rows_to_append = []

        for book in books:
            isbn = (book.get("ISBN") or "").strip()
            title = (book.get("Title") or "").lower().strip()
            author = (book.get("Author") or "").lower().strip()

            # Dedup check
            is_duplicate = False
            if isbn and isbn not in ("", "N/A") and isbn in existing_isbns:
                is_duplicate = True
            elif (title, author) in existing_title_author:
                is_duplicate = True

            if is_duplicate:
                skipped.append(book)
                logger.info(f"Skipped duplicate: {book.get('Title')}")
                continue

            # Prepare row
            date_added = datetime.now().strftime("%Y-%m-%d")
            row = [
                book.get("Title", ""),
                book.get("Author", ""),
                book.get("Year", ""),
                book.get("ISBN", ""),
                book.get("Genre", ""),
                book.get("Pages", ""),
                book.get("Cover URL", ""),
                date_added,
            ]
            rows_to_append.append(row)
            added.append(book)

            # Update dedup sets for within-batch dedup
            if isbn and isbn not in ("", "N/A"):
                existing_isbns.add(isbn)
            if title and author:
                existing_title_author.add((title, author))

        # Batch append
        if rows_to_append:
            sheet.append_rows(rows_to_append, value_input_option="USER_ENTERED")
            logger.info(f"Added {len(rows_to_append)} books to sheet")

        return added, skipped
